title: Meccha Chameleon Mod Installer
description: >-
  Install and update your Meccha Chameleon modpacks and custom maps in just a single click.
  Skip the manual extraction and let this clean, lightweight assistant handle the setup for you.

remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

show_downloads: true
github:
  zip_url: https://github.com/stabldev/meccha-chameleon-mod-installer/releases/latest/download/meccha_chameleon_mod_installer.exe
  tar_url: https://github.com/stabldev/meccha-chameleon-mod-installer/releases
